### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wuhe12** [revenol/DDLO#7]
Dear author:
         I am very interested in your code, but I wonder how the dataset to create. Can you give me some description?

**Comment by revenol** [comment]
The channel gains are randomly generated according to the wireless model described in the paper. The generation of optimal offloading solutions is some kind of 'stupid' and time-consuming. We enumerated all possible 0 and 1 combinations and chose the optimal one.

**Comment by wuhe12** [comment]
Thank you! With best wishes!

**Comment by wuhe12** [comment]
Thank you for your reply! With best wishes!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Liang HUANG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 下午2:13
收件人:&nbsp;"revenol/DDLO"<DDLO@noreply.github.com&gt;;
抄送:&nbsp;"﹏眼泪结成冰〃 "<943091165@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [revenol/DDLO] dataset (#7)




The channel gains are randomly generated according to the wireless model described in the paper. The generation of optimal offloading solutions is some kind of 'stupid' and time-consuming. We enumerated all possible 0 and 1 combinations and chose the optimal one.
