### ISSUE TITLE
tensorflow version，pandas version and scipy version

### ISSUE THREAD

**Issue by john826** [revenol/DDLO#8]
编程环境中所用的python，以及相关库的版本

**Comment by bug-author** [comment]
Can you specify the `tensorflow` version in `README.md` or in `requirements.txt` @revenol

**Comment by revenol** [comment]
Thanks for your suggestion. The README is updated.

The DDLO is implemented based on Tensorflow 1.x in 2018. Please find some insight from https://github.com/revenol/DROO if you wanna update and run the code  on Tensorflow 2 or PyTorch.
